---
title: "normalize_text"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{normalize_text}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ZHAWTools4R)
library(dplyr)
```
Example Data

```{r}
test_data <- tribble(
  ~raw_values, ~other_values,
  "Bevölkerung   des   Bundesamt für Statistik", 42,
  "Bundesamt     für Statistik, SAKE", 2,
  "Bundesamt     für Statistik", 2,
  "BSF", 4,
)

lookup_table <- tribble(
  ~raw, ~key,
  "bundesamt für statistik", "bsf",
  "bsf", "bsf",
  "bevölkerung des bundesamt für statistik", "bsf.bv",
  "sake", "sake"
) 



lookup_table2 <- tribble(
  ~raw1, ~key1,
  "bundesamt für statistik", "bsf",
  "bsf", "bsf",
  "bevölkerung des bundesamt für statistik", "bsf.bv",
  "sake", "sake"
) 

```



```{r}
normalize_text(test_data$raw_values, lookup_table)
```
```{r}
normalize_text(test_data$raw_values, lookup_table2, key="key1", raw="raw1")
```
