---
title: "relabel_for_plots"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{relabel_for_plots}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ZHAWTools4R)
library(tidyverse)
```
Example Data

```{r}
test_data <- tribble(
  ~raw_values, ~other_values,
  "Bevölkerung   des   Bundesamt für Statistik", 42,
  "Bundesamt     für Statistik, SAKE", 2,
  "Bundesamt     für Statistik", 2,
  "BSF", 4,
)

lookup_table <- tribble(
  ~raw, ~key,
  "bundesamt für statistik", "bsf",
  "bsf", "bsf",
  "bevölkerung des bundesamt für statistik", "bsf.bv",
  "sake", "sake"
) 

lookup_labels <- tribble(
  ~key, ~label,
  "bsf", "Bundesamt für Statistik",
  "bsf.bv", "Bevölkerungsstatistik des Bundesamt für Statistik",
  "sake", "SAKE"
)

```



```{r}
test_data <-  test_data %>%
  mutate(key = normalize_text(raw_values, lookup_table, pattern="raw", replacement="key"))
         
test_data
```

```{r}
test_data <- test_data %>%
  mutate(label = relabel_values(key, lookup_labels, pattern = "key", replacement = "label"))

test_data
```
